version: "3.8"

services:
  springboot-app:
    image: sahilphatangare/fire-wizard:latest  # Ensure this image is pushed to Docker Hub
    ports:
      - "8088:8088"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://alibou:alibou@mongodb:27017/chat_app?authSource=admin
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alibou
      - MONGO_INITDB_ROOT_PASSWORD=alibou
    volumes:
      - mongo:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=alibou
      - ME_CONFIG_MONGODB_ADMINPASSWORD=alibou
      - ME_CONFIG_MONGODB_SERVER=mongo_db
    networks:
      - backend

volumes:
  mongo:

networks:
  backend:
    driver: bridge
